### ISSUE TITLE
Make Store#mutate public

### ISSUE THREAD

**Issue by pburgmer** [w11k/Tydux#17]
Sometimes it is annoying to manually expose multiple mutator methods via a store method. It highly depends on the use case. Sometime you want to hide the mutator, sometime you want to expose it. Couldn't Tydux offer both? To different types of Store, one with public mutator, one with protected. Then the developer can decide for each store how to behave.

**Comment by romanroe** [comment]
@pburgmer 

What about a util method that turns a mutator instance into a store. Something like:

```
const simpleStore = createStoreFromMutator(mutator);
```

This way the two use cases are clearly separated. I wouldn't like a mixture of both, e.g. a store with own methods and an exposed mutate member at the same time.

**Comment by pburgmer** [comment]
@romanroe 
Wouldn't fit my use case. I need some complex methods on the service, especially resusable selects. Why don't you want exposed mutator methods an own methods at the same time? I don't see a problem. They are still separated by the .mutate between store and method.

**Comment by romanroe** [comment]
@pburgmer 

1. The user doesn't know if an action requires to be in the store class or mutator class and most importantly, he doesn't care. When a store provides own methods as well as a public mutate member, the user of the store would always need to check both to see what the store is capable of.

2. Your problem also exist in the server side with services and DAOs. Some service methods will always be stupid delegates to the DAO but it would always be a bad design/architecture to bypass the service and directly access the DAO in e.g. an MVC controller.

3. An important design goal of Tydux is to promote a good store architecture. For simple stores, this architecture might feel overkill. Weakening these rules might help in a simple case but hurt in complex cases.

**Comment by romanroe** [comment]
@pburgmer 

4. You can always provide a store member such as `dispatch` that provides a reference to `this.mutate`.

**Comment by pburgmer** [comment]
@romanroe 
That's nice! We should add this as a tip to the documentation. And explain why that's not the default ;)

**Comment by romanroe** [comment]
@pburgmer Do you mind starting a tips&tricks&howto document?

**Comment by pburgmer** [comment]
@romanroe Sounds good
