### ISSUE TITLE
Make ObservableSelection pipeable

### ISSUE THREAD

**Issue by pburgmer** [w11k/Tydux#18]
If you want to offer a special selection via a store method you have three options right now:
1 ) do everything in the select function
2) unbound the ObservableSelection
3) pass the bound operator to the service as a parameter and use it to bound the ObservableSelection

All these options are not ideal.
1) leads to spaghetti code. we want to be able to use all the cool Rx operators
2) nullifies the benefit of ObservableSelection, the callee gets a standard Observable
3) is two complicated

Proposal:

ObservableSelection should have a pipe method like an Observable. These method can be used with the standard Rx operators but returns an ObservableSelection.

**Comment by romanroe** [comment]
Added `ObservableSelection.pipe()` in 8.0.3
