### ISSUE TITLE
Facade Generic in different order than super constructor call

### ISSUE THREAD

**Issue by sengmann** [w11k/Tydux#24]
For example:

```typescript
export class LoadingService extends Facade<LoadingState, LoadingCommands> {

  constructor(tydux: TyduxStore) {
    super(tydux, 'loading',` new LoadingCommands(), new LoadingState()`);
  }
}
```

**Comment by sengmann** [comment]
Fixing this issue is only possible by breaking changes. In context of angular we could provide an update schematic. For non Angular users [codemod](https://github.com/facebook/codemod) or [ts-codemod](https://github.com/tusharmath/ts-codemod) could be an alternative.

**Comment by romanroe** [comment]
Obsolete since 14.0.0
