### ISSUE TITLE
Bump peer dependency of @w11k/rx-ninja

### ISSUE THREAD

**Issue by sengmann** [w11k/Tydux#26]
The current version of Tydux still uses @w11k/rx-ninja in version 1.8.3. in the meantime there is already the fourth version of rx-ninja. We should adjust the peer dependency of Tydux accordingly.

**Comment by sengmann** [comment]
Was released with 12.0.0

**Comment by pburgmer** [comment]
Hi Sascha,

The published version of @w11k/rx-ninja now has fixed peer dependency to 4.0.2. Meanwhile rx-ninja is at 4.1.0 which results in a warning on running npm install.

**Comment by sengmann** [comment]
fixed in 14.1.1
